// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMg6q1VKJYClhiWZhc4J_7SSUwHJUWYg',
    appId: '1:725810575327:web:15ea6ce7d4c6dc09e0766a',
    messagingSenderId: '725810575327',
    projectId: 'fir-practice-1391c',
    authDomain: 'fir-practice-1391c.firebaseapp.com',
    storageBucket: 'fir-practice-1391c.appspot.com',
    measurementId: 'G-TMW09NZG55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5uEMLvl3FB3T1vs1OnEJFf3J2d0U3HAw',
    appId: '1:725810575327:android:8eab1a4ab02f0ef5e0766a',
    messagingSenderId: '725810575327',
    projectId: 'fir-practice-1391c',
    storageBucket: 'fir-practice-1391c.appspot.com',
  );
}
